name = "MyExample"
uuid = "cc1d54b9-dd7b-4707-a2e3-3337477813ae"
authors = ["Martin Andersson"]
version = "0.1.0"

[deps]
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"

[compat]
Zygote = "0.6"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
